### ISSUE TITLE
Seite Fakten

### ISSUE THREAD

**Issue by florianredmann** [webD97/fori-webapp#8]
Die in #6 erwähnten Fun Facts sollen aus einer Sammlung an Fakten kommen. Diese Sammlung soll eine eigene Seite bekommen.

**Comment by webD97** [comment]
Was macht einen Fakt datenstrukturmäßig (😁) aus? Klar, der Content, aber sonst noch was?

**Comment by webD97** [comment]
Optisch könnte ich mir irgendwas Card-mäßiges ganz gut vorstellen: https://material-ui.com/components/cards/

**Comment by florianredmann** [comment]
Das mit den Cards ist eine gute Idee. Als Fakt denke ich einfach nur eine ID und der Content per se.

**Comment by webD97** [comment]
Wozu die ID? Ich hätte die Fakten jetzt spontan als Array von Objekten abgebildet, dann kann man es bei Bedarf später noch erweitern.

Am 28.08.2019 10:38 schrieb Florian Redmann <notifications@github.com>:

Das mit den Cards ist eine gute Idee. Als Fakt denke ich einfach nur eine ID und der Content per se.

**Comment by florianredmann** [comment]
Oder so. Auf jeden Fall ist die Datenstruktur eher schlank.
